package de.lineas.training.publisher.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Entry service. Represents a row in the &quot;PUB_Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.lineas.training.publisher.model.impl.EntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.lineas.training.publisher.model.impl.EntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Entry
 * @see de.lineas.training.publisher.model.impl.EntryImpl
 * @see de.lineas.training.publisher.model.impl.EntryModelImpl
 * @generated
 */
public interface EntryModel extends BaseModel<Entry> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entry model instance should use the {@link Entry} interface instead.
     */

    /**
     * Returns the primary key of this entry.
     *
     * @return the primary key of this entry
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this entry.
     *
     * @param primaryKey the primary key of this entry
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this entry.
     *
     * @return the uuid of this entry
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this entry.
     *
     * @param uuid the uuid of this entry
     */
    public void setUuid(String uuid);

    /**
     * Returns the entry ID of this entry.
     *
     * @return the entry ID of this entry
     */
    public long getEntryId();

    /**
     * Sets the entry ID of this entry.
     *
     * @param entryId the entry ID of this entry
     */
    public void setEntryId(long entryId);

    /**
     * Returns the txt of this entry.
     *
     * @return the txt of this entry
     */
    @AutoEscape
    public String getTxt();

    /**
     * Sets the txt of this entry.
     *
     * @param txt the txt of this entry
     */
    public void setTxt(String txt);

    /**
     * Returns the group ID of this entry.
     *
     * @return the group ID of this entry
     */
    public long getGroupId();

    /**
     * Sets the group ID of this entry.
     *
     * @param groupId the group ID of this entry
     */
    public void setGroupId(long groupId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Entry entry);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Entry> toCacheModel();

    @Override
    public Entry toEscapedModel();

    @Override
    public Entry toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
