package de.lineas.training.herodb.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.lineas.training.herodb.model.Power;
import de.lineas.training.herodb.service.PowerLocalServiceUtil;

/**
 * The extended model base implementation for the Power service. Represents a row in the &quot;hero_Power&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PowerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PowerImpl
 * @see de.lineas.training.herodb.model.Power
 * @generated
 */
public abstract class PowerBaseImpl extends PowerModelImpl implements Power {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a power model instance should use the {@link Power} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PowerLocalServiceUtil.addPower(this);
        } else {
            PowerLocalServiceUtil.updatePower(this);
        }
    }
}
